const listTemplates = [
    {name: "fa_afa", 
    "preheader" : ["pre3"], 
    "header" : ["head1"],
    "body" : ["body3","body4"]},
    {name: "service", 
        "preheader" : ["pre2"], 
        "header" : ["head2"],
        "body" : ["body1","body2"]},
    {name: "marketing1", 
        "preheader" : ["pre1"],
        "logo" : ["log1"],
        "header" : ["head1"],
        "body" : ["body1","body3", "body5"],
        "rating_social_legal" : ["rating1","body3", "social_legal1"]},
    {name: "marketing2", 
        "preheader" : ["pre5"], 
        "logo" : ["log9"],
        "header" : ["head2"],
        "body" : ["body2","body3", "body6", "body7", "body9"],
        "rating_social_legal" : ["rating1","body3", "social_legal1"]},
    {name: "marketing3", 
        "preheader" : ["pre1"], 
        "logo" : ["log5"],
        "header" : ["head3"],
        "body" : ["body1","body3", "body9"],
        "rating_social_legal" : ["rating1","body3", "social_legal1"]},
]

export default listTemplates;

